# Generated by Django 5.1.6 on 2025-03-09 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(default='#1FD7C1', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(blank=True, max_length=100)),
                ('is_tasked_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(choices=[('feedback', 'Feedback'), ('todo', 'To Do'), ('progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='Medium', max_length=20)),
                ('type', models.CharField(choices=[('Technical Task', 'Technical Task'), ('User Story', 'User Story')], default='User Story', max_length=20)),
                ('subtasks', models.ManyToManyField(blank=True, to='join.subtask')),
                ('assigned', models.ManyToManyField(blank=True, to='join.user')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
