# Generated by Django 5.1.6 on 2025-03-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_subtask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.ManyToManyField(blank=True, to='join.contacts'),
        ),
    ]
